version: "3.9"

services:

    # WORDPRESS
    wordpress:
        container_name: wordpress_${PROJECT_NAME}
        image: wordpress:php${PHP_VERSION}-apache
        restart: always
        stdin_open: true
        tty: true
        hostname: ${PROJECT_DOMAIN}
        ports:
            - ${WP_PORT}:80
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
        volumes:
            - ${WWW_DATA_DIR}:/var/www/html
        networks:
            - internal

    # DATABASES    
    mysql:
        container_name: mariadb_${PROJECT_NAME}
        image: mariadb
        restart: always
        command: --max_allowed_packet=256M
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${MYSQL_DATA_DIR}:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - internal

#     mysql:
#         container_name: mysql_${PROJECT_NAME}
#         image: mysql:8.0
#         command: --default-authentication-plugin=mysql_native_password  
#         expose:
#        - "3306"
#        restart: unless-stopped
#        environment:
#            MYSQL_DATABASE: ${MYSQL_DATABASE}
#            MYSQL_USER: ${MYSQL_USER}
#            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
#        volumes:
#            - ${MYSQL_DATA_DIR}:/var/lib/mysql

    # WP-CLI
    wordpress-cli:
        container_name: wpcli_${PROJECT_NAME}
        depends_on:
        - mysql
        - wordpress
        image: wordpress:cli
        # vstm: This is required to run wordpress-cli with the same user-id as wordpress. 
        user: xfs
        # vstm: add shared volume
        volumes:
        - ${WWW_DATA_DIR}:/var/www/html
    
    # WEBSERVER
#    nginx:
#        container_name: nginx_${PROJECT_NAME}
#        image: nginx:latest
#        restart: unless-stopped
#        ports:
#            - ${NGINX_PORT}:80
#            - ${NGINX_SSL_PORT}:443
#        volumes:
#            - ${NGINX_CONF_DIR}:/etc/nginx/conf.d
#            - ${CERT_CONF_DIR}:/etc/nginx/ssl
#            - ${WWW_DATA_DIR}:/var/www/html
#         networks:
#            - proxy
#            - internal

#    litespeed:
#        container_name: openlitespeed_${PROJECT_NAME}
#        image: litespeedtech/openlitespeed:${OLS_VERSION}-${PHP_VERSION}
#        logging:
#        driver: none
#        volumes:
#            - ${OLS_DATA_DIR}/lsws/conf:/usr/local/lsws/conf
#            - ${OLS_DATA_DIR}/lsws/admin-conf:/usr/local/lsws/admin/conf
#            - ${OLS_DATA_DIR}/bin/container:/usr/local/bin
#            - ${OLS_DATA_DIR}/sites:/var/www/vhosts/
#            - ${OLS_DATA_DIR}/acme:/root/.acme.sh/
#            - ${OLS_DATA_DIR}/logs:/usr/local/lsws/logs/
#        ports:
#        - 80:80
#        - 443:443
#        - 443:443/udp
#        - 7080:7080
#        restart: always
#        environment:
#        TZ: ${TimeZone}
#         networks:
#            - proxy
#            - internal

    # REDIS
    wpredis:
        container_name: redis_${PROJECT_NAME}
        image: redis:6
        restart: unless-stopped
        volumes:
            - ${REDIS_DATA}:/data
        networks:
            - internal
    
    # PHPMYADMIN
    phpmyadmin:
        container_name: phpmyadmin_${PROJECT_NAME}
        image: phpmyadmin/phpmyadmin
        ports:
        - 8080:80
        - 8443:443
        hostname: ${PHPMYADMIN_DOMAIN}
        environment:
            PMA_HOST: mysql
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD: ${MYSQL_PASSWORD} 
        restart: always
        volumes:
            - ${PHPMYADMIN_DATA}:/data
        networks:
            - internal
    
    # CERTBOT
    certbot:
        container_name: certbot_${PROJECT_NAME}
        image: certbot/certbot:latest
        #command: certonly --webroot --webroot-path=/var/www/html --email ${CERT_EMAIL} --agree-tos --no-eff-email -d domain.com -d www.domain.com
        volumes:
            - ${CERT_CONF_DIR}:/etc/letsencrypt
            - ${CERT_LOGS_DIR}:/var/log/letsencrypt
            - ${WWW_DATA_DIR}:/var/www/html

networks:
  internal:
    name: network_${PROJECT_NAME}
    driver: bridge
#    external: true

#volumes:
#    db_data:
#    wordpress_data: